title = 'Pipeline Configurations and Settings'

[parsing]

[parsing.schools]
'wyoming' = 'University of Wyoming'
'stanford' = 'Stanford University'
'south carolina' = 'University of South Carolina'
'tulsa' = 'University of Tulsa'
'tcu' = 'TCU'
'san jose st.' = 'State University of San Jose'
'ucla' = 'UCLA'
'smu' = 'SMU'
'duke' = 'Duke University'
'louisville' = 'University of Louisville'
'arkansas' = 'University of Arkansas'
'kansas' = 'Univerity of Kansas'
'texas a&amp;m' = 'Texas A&M University'
'georgia southern' = 'Georgia Southern University'
'penn st.' = 'Pennsylvania State University'
'villanova' = 'Villanova University'
'baylor' = 'Baylor University'
'northern iowa' = 'University of Northern Iowa'
'georgia' = 'University of Georgia'
'southeast missouri' = 'University of Southeast Missouri'
'central florida' = 'University of Central Florida'
'temple' = 'Temple University'
'maryland' = 'University of Maryland'
'wisconsin' = 'University of Wisconsin-Madison'
'Wisconsin' = 'University of Wisconsin-Madison'
'florida' = 'University of Florida'
'iowa' = 'University of Iowa'
'louisiana state' = 'Louisiana State University'
'texas' = 'University of Texas at Austin'
'toledo' = 'University of Toledo'
'pittsburgh' = 'University of Pittsburgh'
'alabama' = 'University of Alabama'
'assumption' = 'Assumption University'
'weber st.' = 'Weber State University'
'syracuse' = 'Syracuse University'
'utah' = 'University of Utah'
'iowa st.' = 'State University of Iowa'
'mississippi' = 'University of Mississippi'
'clemson' = 'Clemson University'
'buffalo' = 'University at Buffalo'
'appalachian st.' = 'Appalachian State University'
'boston col.' = 'Boston College'
'bowling green' = 'Bowling Green State University'
'missouri' = 'University of Missouri'
'backsonville st.' = 'Jacksonville State University'
'coastal carolina' = 'Coastal Carolina University'
'houston' = 'University of Houston'
'oklahoma' = 'University of Oklahoma'
'oregon st.' = 'Oregon State University'
'washington' = 'University of Washington'
'miami (fl)' = 'University of Miami'
'virginia tech' = 'Virginia Tech'
'boise state' = 'Boise State University'
'vanderbilt' = 'Vanderbilt University'
'connecticut' = 'University of Connecticut'
'tennessee' = 'University of Tennessee'
'lsu' = 'LSU'
'tulane' = 'Tulane University'
'texas-san antonio' = 'University of Texas at San Antonio'
'louisiana tech' = 'Louisiana Institute of Technology'
'notre dame' = 'University of Notre Dame'
'washington st.' = 'Washington State University'
'west. michigan' = 'Western Michigan University'
'western michigan' = 'Western Michigan University'
'florida state' = 'Florida State University'
'alcorn state' = 'Alcorn State University'
'east. illinois' = 'East Illinois University'
'ohio st.' = 'Ohio State University'
'southern illinois' = 'University of Southern Illinois'
'illinois' = 'University of Illinois'
'nebraska' = 'University of Nebraska-Lincoln'
'north carolina state' = 'UNC'
'oklahoma st.' = 'Oklahoma State University'
'north dakota state' = 'North Dakota State University'
'oregon' = 'University of Oregon'
'colorado' = 'Colorado State University'
'indiana' = 'Indiana University Bloomington'
'michigan' = 'University of Michigan'
'auburn' = 'Auburn University'
'nevada' = 'University of Nevada at Reno'
'northwestern' = 'Northwestern University'
'virginia' = 'Virginia State University'
'ohio state' = 'Ohio State University'
'ucf' = 'UCF'
'nevada-reno' = 'University of Nevada at Reno'
'purdue' = 'Purdue University'
'arizona' = 'Arizona State University'
'texas-el paso' = 'University of Texas at El Paso'
'wake forest' = 'Wake Forest University'
'west virginia' = 'University of West Virginia'
'southern california' = 'USC'
'mississippi state' = 'Mississipi State University'
'cincinnati' = 'University of Cincinnati'
'pennsylvanua' = 'University of Pennsylvania'
'texas tech, texas a&m' = 'Texas Tech University, Texas A&M University'
'tennessee-martin' = 'UTM'
'north texas' = 'University of North Texas'
'charlotte' = 'University of Charlotte'
'duquesne' = 'Duquesne University'
'southern utah' = 'University of Southern Utah'
'San Diego State' = 'San Diego State University'
'north carolina' = 'UNC'
'michigan state' = 'State University of Michigan'
'montana' = 'University of Montana'
'rice' = 'Rice University'
'memphis' = 'University of Memphis'
'washington state' = 'State University of Washington'
'lane' = 'Lane College'
'northern colorado' = 'University of Northern Colorado'
'south alabama' = 'University of South Alabama'
'western state (colo.)' = 'University of Western Colorado'
'rutgers' = 'Rutgers University'
'texas christian' = 'Christian University of Texas'
'california-davis,ucla' = 'UC Davis, UCLA'
'james madison' = 'James Madison College'
'stetson' = 'Stetson University'
'old dominion' = 'Old Dominion College'
'samford' = 'Samford College'
'sioux falls' = 'Sioux Falls University'
'presbyterian' = 'Presbyterian University'
'brigham young' = 'Brigham Young College'